version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - app-networks
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "words:2:1, words-count:2:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9094:9094
    depends_on:
      - zookeeper
    networks:
      - app-networks
  spark:
    image: bitnami/spark
    container_name: spark
    volumes:
      - ./spark-word-count/target/SparkStreamingDemo-V1-jar-with-dependencies.jar:/app/jars/SparkStreamingDemo-V1-jar-with-dependencies.jar
    networks:
      - app-networks
      
  jobmanager:
    container_name: jobmanager
    hostname: jobmanager
    image: flink:latest
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - app-networks

  taskmanager:
    container_name: taskmanager
    hostname: taskmanager
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - app-networks
networks:
  app-networks:
    driver: bridge